name: "Audit Reporting Workflow"

on:
  workflow_call:
    secrets:
      azure-sp-credentials:
        required: true

jobs:
  audit:
    name: Audit Report Job

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Configure Git"
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com

      - name: "Git Pull"
        run: |
          git pull

      - name: "Setup DotNet Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Install Latest azure-audit-cli Tool from MS Nuget"
        run: dotnet tool install --global azure-audit-cli

      - name: "Upgrade Azure CLI"
        continue-on-error: true
        run: az upgrade --yes

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Show Azure CLI Version"
        run: az --version

      - name: "Run Audit CLI on All Resources"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-audit all --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/all-resources.md; fi

      - name: "Run Audit CLI on Networking Resources"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-audit networking --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/networking-resources.md; fi

      - name: "Run Audit CLI on Storage Resources"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-audit storage --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./audit-reports/storage-resources.md; fi

      - name: "Commit and Push Command Outputs"
        continue-on-error: true
        run: |
          git pull
          git add -A .
          git commit -m "Generated reports [skip ci]"
          git push
