name: "Cost Reporting Workflow"

on:
  workflow_call:
    secrets:
      azure-sp-credentials:
        required: true

jobs:
  create-summary-reports:
    name: "Create Summary Reports"
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Setup DotNet Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Install Latest azure-cost-cli Tool from MS Nuget"
        run: dotnet tool install --global azure-cost-cli

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Run Daily Cost Report"
        run: azure-cost dailyCosts --dimension ResourceGroup --output Markdown > ./cost-reports/daily-costs.md

      - name: "Run Cost by Resource Report"
        run: azure-cost costByResource --output Markdown > ./cost-reports/cost-by-resource.md

      - name: "Run Accumulated Cost Report for All Resources"
        run: azure-cost accumulatedCost --output Markdown > ./cost-reports/accumulated-cost.md

      - name: "Run Accumulated Cost Report for Each Resource"
        run: ./.github/scripts/accumulated-cost-by-resource.sh "summary-only"

      - name: "Configure Git"
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com

      - name: "Commit and Push Command Outputs"
        run: |
          git pull
          git add -A .
          git commit -m "Generated reports [skip ci]"
          git push


  create-matrix:
    name: "Create Resource Group Matrix"
    runs-on: ubuntu-latest
    outputs:
      resource-groups: ${{ steps.get-resource-groups.outputs.resource-groups }}

    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Get Resource Groups"
        id: get-resource-groups
        run: |
          RESOURCE_GROUPS_JSON=$(./.github/scripts/resource-groups-as-json.sh);
          echo "::set-output name=resource-groups::$RESOURCE_GROUPS_JSON";

  cost:
    name: "Cost Report Job for Group: ${{ matrix.group }}"
    needs: create-matrix
    strategy:
      matrix:
        group: ${{ fromJson(needs.create-matrix.outputs.resource-groups) }}
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Setup DotNet Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Install Latest azure-cost-cli Tool from MS Nuget"
        run: dotnet tool install --global azure-cost-cli

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Run Accumulated Cost Report for Each Resource"
        run: ./.github/scripts/accumulated-cost-by-resource.sh "${{ matrix.group }}"

      - name: "Configure Git"
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com

      - name: "Commit and Push Command Outputs"
        run: |
          git pull
          git add -A .
          git commit -m "Generated reports [skip ci]"
          git push
