name: "Cost Reporting Workflow"

on:
  workflow_call:
    secrets:
      azure-sp-credentials:
        required: true

jobs:
  create-matrix:
    name: "Create Resource Group JSON"
    runs-on: ubuntu-latest
    outputs:
      resource-groups: ${{ steps.get-resource-groups.outputs.resource-groups }}

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Get Resource Groups as JSON and Encode to Base64"
        id: get-resource-groups
        run: |
          RESOURCE_GROUPS_JSON=$(./.github/scripts/resource-groups-as-json.sh);
          RG_JSON_B64="$(echo $RESOURCE_GROUPS_JSON | base64 -w0 -)";
          echo "resource-groups=$RG_JSON_B64" >> $GITHUB_OUTPUT;

  decode:
    name: "Decode JSON"
    needs: create-matrix
    outputs:
      resource-groups: ${{ steps.decode-json.outputs.resource-groups }}
    runs-on: ubuntu-latest

    steps:
      - name: "Decode JSON from Base64"
        id: decode-json
        run: |
          JSON="$(echo '${{ needs.create-matrix.outputs.resource-groups }}' | base64 -di)";
          echo "resource-groups=$JSON" >> $GITHUB_OUTPUT;
          echo "$JSON";
    
  cost:
    name: "Cost Report Job for Group: ${{ matrix.group }}"
    needs: decode
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.decode.outputs.resource-groups) }}
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Setup DotNet Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Install Latest azure-cost-cli Tool from MS Nuget"
        run: dotnet tool install --global azure-cost-cli

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Run Accumulated Cost Report for Each Resource"
        continue-on-error: true
        run: ./.github/scripts/accumulated-cost-by-resource.sh "${{ matrix.group }}"

      - name: "Configure Git"
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com

      - name: "Commit and Push Command Outputs"
        continue-on-error: true
        run: |
          git pull
          git add -A .
          git commit -m "Generated reports [skip ci]"
          git push

  create-summary-reports:
    name: "Create Summary Reports"
    needs: cost
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Setup DotNet Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: "Install Latest azure-cost-cli Tool from MS Nuget"
        run: dotnet tool install --global azure-cost-cli

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-sp-credentials }}

      - name: "Run Daily Cost Report"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-cost dailyCosts --dimension ResourceGroup --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/daily-costs.md; fi

      - name: "Run Cost by Resource Report"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-cost costByResource --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/cost-by-resource.md; fi

      - name: "Run Accumulated Cost Report for All Resources"
        continue-on-error: true
        run: |
          OUTPUT=$(azure-cost accumulatedCost --output Markdown)
          if [ $? -eq 0 ]; then echo "$OUTPUT" > ./cost-reports/accumulated-cost.md; fi

      - name: "Run Summary Report Generation"
        continue-on-error: true
        run: ./.github/scripts/accumulated-cost-by-resource.sh "summary-only"

      - name: "Configure Git"
        run: |
          git config user.name jpfulton
          git config user.email jpatrick.fulton@gmail.com

      - name: "Commit and Push Command Outputs"
        continue-on-error: true
        run: |
          git pull
          git add -A .
          git commit -m "Generated reports [skip ci]"
          git push

        
